# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "02a87baed64f16e9cc624497c8bcbe27"
name = "zync-payment-customizations"
handle = "zync-payment-customizations"
application_url = "https://dem-pizza-playlist-indicator.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "kb-quiz-store-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dem-pizza-playlist-indicator.trycloudflare.com/auth/callback",
  "https://dem-pizza-playlist-indicator.trycloudflare.com/auth/shopify/callback",
  "https://dem-pizza-playlist-indicator.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
